### ISSUE TITLE
Spell checker triggers?

### ISSUE THREAD

**Issue by neilsustc** [bartosz-antosik/vscode-spellright#213] opened 2018-09-25 20:24 UTC
It is really confused when the checker will be triggered 🤔

![recheck](https://user-images.githubusercontent.com/7588612/46040716-ffc80d80-c108-11e8-8881-edf89ab5740d.gif)

My settings

```json
{
    "spellright.documentTypes": [
        "markdown",
        "latex",
        "plaintext",
        "python",
        "html"
    ],
    "spellright.ignoreRegExps": [
        "/[\\u4e00-\\u9eff]+/g",
        "/<style>[^]*?</style>/gm",
        "/<script>[^]*?</script>/gm",
        "/&(nbsp|emsp);/g"
    ],
    "spellright.ignoreRegExpsByClass": {
        "html": [
            "/(href|<br>)/g"
        ],
        "markdown": [
            "/\\$.+?\\$/gm"
        ]
    },
    "spellright.language": "en",
    "spellright.notificationClass": "warning",
    "spellright.statusBarIndicator": false,
}
```

Version: 1.28.0-insider (user setup)
Commit: fe8d9d2470ddffb9dc2da604b23f5bd8a185cd66
Date: 2018-09-25T05:31:33.193Z
on Windows 10

**Comment by neilsustc** [comment] 2018-09-26 07:38
The empty document is created before the screen capture.
Open the document and type something (It seems that `helllo` is marked misspelled unless you reopen the document?)
Reopen the document and then it is checked
Then do vscode's "copy line down/up" command, they won't be marked
(Reopen to get them checked again)
Delete each word using `ctrl+backspace/delete`, the green markers remain

Actually, I suspect it is the problem of updating diagnostic info. I can see the light bulbs as I make changes to the document but the green lines are not updated.

**Comment by bartosz-antosik** [comment] 2018-09-26 14:56
I cannot reproduce this in regular version. It does however happen exactly as you describe it `insiders` build. 

I am sorry but I suspect this is a transient state so I will not rather fight with this. I will let myself close this and we will see in the next regular release.

**Closed by bartosz-antosik** 2018-09-26 14:56 UTC
Labels: help wanted

**Comment by neilsustc** [comment] 2018-09-26 15:03
I see. However, this month's vscode development comes to the "code freeze" stage now. I guess this issue will exist in the regular build soon 😂

**Comment by neilsustc** [comment] 2018-10-10 12:46
upvoted 😀
