### ISSUE TITLE
Ignore URL's in spellcheck

### ISSUE THREAD

**Issue by jeffreymeng** [bartosz-antosik/vscode-spellright#113] opened 2018-02-08 04:11 UTC
It seems that, in html at least, URL's(inside comments) are also spellchecked.

![2018-02-07_20-10-24](https://user-images.githubusercontent.com/15185258/35955230-f2b73eca-0c42-11e8-8d6c-7f25b6d5e16d.png)

Is this expected? I'm guessing that most URL's will not be spelled correctly, so it seems that url's should be ignored in spell checking.

**Comment by bartosz-antosik** [comment] 2018-02-08 08:25
It is not supposed to happen. Could you please provide some more data on this, preferably a sample document in text format pasted into item description so that I could reproduce this?

![image](https://user-images.githubusercontent.com/20492548/35962500-f9bac006-0cb1-11e8-84fb-e2582b115c58.png)

**Comment by jeffreymeng** [comment] 2018-02-09 01:11
this also seems to happen with emails.

Here's some html that triggers the error(i cropped out some of the text,but left the things that cause the error): [https://gist.github.com/jeffreymeng/53e3fb1597f216a6ccb99a430b5731ba](https://gist.github.com/jeffreymeng/53e3fb1597f216a6ccb99a430b5731ba).

I also took images of the actual spell check and the config.

The spelling errors are on lines 55, 58, 60, 61, 63.

Lines 1-39:
![2018-02-08_17-05-50](https://user-images.githubusercontent.com/15185258/36006592-b5e50760-0cf2-11e8-9193-533e839a1e0e.png)
Lines 35-End:
![2018-02-08_17-06-01](https://user-images.githubusercontent.com/15185258/36006598-be4b571a-0cf2-11e8-872f-f2c7c9fde3a0.png)
Config:
![2018-02-08_17-06-28](https://user-images.githubusercontent.com/15185258/36006602-c3890eb6-0cf2-11e8-9c5b-d28e1dfec7c9.png)
Also the version info:
![2018-02-08_17-10-07](https://user-images.githubusercontent.com/15185258/36006635-f408ae34-0cf2-11e8-876d-253bf26b619d.png)

**Comment by jeffreymeng** [comment] 2018-02-09 01:26
Also, is there a way to be able to only spellcheck the html portion of an html document?

**Comment by bartosz-antosik** [comment] 2018-02-09 08:38
Great many thanks for the examples! They revealed that because of some incredible omission URLs were not eliminated from XML parser. It will be corrected within next build. Should be today.

The reason it did not show in my tests was that your dictionaries (on macOS I suppose) do not understand "stackoverflow" whereas mine (on Windows) do. 

In the above example last URL will still be marked as misspelled:

```
<p>
https://stackoverflow .com/a/26245056/5511561 
</p>
```

because it is a malformed URL (space before .com) which does not fit the regular expression that eliminates URLs.

For the answer on the other question see answer below.

**Comment by bartosz-antosik** [comment] 2018-02-09 09:03
There are many ways to eliminate parts of document from spelling. Please have a look to the README document under the following sections:

## Settings

`spellright.spellContext: ""`
`spellright.spellContextByClass: {}`

`spellright.ignoreRegExps: []`
`spellright.ignoreRegExpsByClass: {}`

## In-Document commands:

`spellcheck-off` 
`spellcheck-on`

For example:

1) You can spell only `body` section of HTML documents and skip spelling comments using:

```JSON
"spellright.spellContextByClass": {
    "html": "body"
}
```

2) You can skip content of <script></script> tag using:

```JSON
"spellright.ignoreRegExpsByClass": {
    "html": [ "/<script>[^]*?</script>/gm" ]
}
```

**Comment by bartosz-antosik** [comment] 2018-02-09 09:19
Let me please know in this thread whether the fix works for you. 

Thanks for review & help tracing the issue.

**Closed by bartosz-antosik** 2018-02-09 09:19 UTC
Labels: help wanted

**Comment by jeffreymeng** [comment] 2018-02-09 22:51
Thank younfo the reply about ignoring.

**Comment by jeffreymeng** [comment] 2018-02-09 22:51
Is the url bug fixed?

**Comment by bartosz-antosik** [comment] 2018-02-09 23:11
Should be. In version 2.1.14.
