### ISSUE TITLE
TypeScript comments not checked

### ISSUE THREAD

**Issue by borekb** [bartosz-antosik/vscode-spellright#77] opened 2017-10-15 15:27 UTC
Probably a regression as this worked before. My config:

```
    "spellright.language": "en",
    "spellright.addToSystemDictionary": true,
    "spellright.notificationClass": "information",
    "spellright.documentTypes": [
        "markdown", "typescript"
    ],
    "spellright.spellContext": "body comments strings",
    "spellright.spellContextByClass": {
        "markdown": "body",
        "typescript": "comment",
        "json": "comment",
        "html": "body"
    },
```

No spell checking in .ts:

![image](https://user-images.githubusercontent.com/101152/31586171-d5607208-b1cd-11e7-8a00-36460f2ecd3d.png)

VSCode 1.17.1
SpellRight 1.2.18

**Comment by bartosz-antosik** [comment] 2017-10-15 15:33
I am pretty sure the problem is that you have `comment` but it should be `comments`. Similarly `strings` not `string`. It was changed after right after initially being introduced with the syntax in singular, as you use. ;-)

Could you please give it a shot & as usually let me know the result?

**Comment by borekb** [comment] 2017-10-15 15:46
I've updated it to this but still no spell checking:

```
    "spellright.documentTypes": [
        "markdown", "typescript"
    ],
    "spellright.spellContext": "body comments strings",
    "spellright.spellContextByClass": {
        "markdown": "body",
        "typescript": "comments",
        "json": "comments",
        "html": "body"
    },
```

**Comment by bartosz-antosik** [comment] 2017-10-15 15:55
Strange. Let me have a look.

**Comment by bartosz-antosik** [comment] 2017-10-15 15:55
It is for sure not overridden by workspace settings?

**Comment by borekb** [comment] 2017-10-15 15:59
My `.vscode/settings.json` doesn't contain any SpellRight configuration.

**Comment by bartosz-antosik** [comment] 2017-10-15 18:23
Do you have any output in DEBUG CONSOLE when you spell TypeScript document?

**Comment by borekb** [comment] 2017-10-15 18:38
No, no output anywhere. I've also tried to remove `spellContextByClass` for `typescript`, it looks like TS files are not checked at all (but I see the "[eye] English" part of the status bar and spell checking Markdown files works as usual).

**Comment by bartosz-antosik** [comment] 2017-10-16 07:57
Thanks for help. It was indeed a regression introduced by #73.

**Comment by bartosz-antosik** [comment] 2017-10-16 08:08
Should be fixed in 1.2.19.

**Closed by bartosz-antosik** 2017-10-16 08:08 UTC
Labels: bug, question

**Comment by bartosz-antosik** [comment] 2017-10-16 08:15
Of course, please let me know if it works for you. ;-)

**Comment by borekb** [comment] 2017-10-16 08:26
Yep, works nicely, thanks!
