### ISSUE TITLE
Spelling hints are broken since v2.4.10

### ISSUE THREAD

**Issue by luav** [bartosz-antosik/vscode-spellright#168] opened 2018-05-20 23:22 UTC
Most of the spelling hints are shown just as underscores since v2.4.10:
![spellright_brokenhints](https://user-images.githubusercontent.com/6162969/40284845-22062400-5c95-11e8-89ce-e1e47858defb.png)

Note that this issues exists not only for the shown uppercase words but also for the mixed and lowercase expressions.

**Comment by bartosz-antosik** [comment] 2018-05-21 08:32
Yes! An regression resulting from the fixes you referenced! Unnoticed because it happens only on HUNSPELL back-end (Linux, Windows 7). Should be fixed in 2.4.12.

**Closed by bartosz-antosik** 2018-05-21 08:32 UTC
