### ISSUE TITLE
Infinite loop problem

### ISSUE THREAD

**Issue by nealot** [bartosz-antosik/vscode-spellright#187] opened 2018-07-27 13:48 UTC
Opening a random project file leads the problems panel to continuously report that there are spelling issues in the file. The spellchecker displays the information for one second before proceeding to close it and then repeating this over and over. I have since uninstalled this extension and Code Spell Checker doesn't seem to have this problem. I'm running the latest insiders build.

**Comment by nealot** [comment] 2018-07-28 11:47
This is basically what happens:

1. I open a Golang file
2. I open the problems panel
3. The problems list is populated with spelling mistakes from the file
4. The problems list is cleared of all spelling mistakes
5. Loop 3-4

**Comment by bartosz-antosik** [comment] 2018-07-30 19:51
I tried to replicate the problem with `Insiders` version few moments ago and I cannot. Not with a Golang file but with some other. Could you please show me a minimal file that does this? Does this happen with other files, like text documents in `Insiders` version?

**Comment by bartosz-antosik** [comment] 2018-08-01 18:49
I am going to close this one as I cannot reproduce the situation.

If you find any more evidence please post in this thread.

**Closed by bartosz-antosik** 2018-08-01 18:49 UTC
Labels: help wanted

**Comment by nealot** [comment] 2018-08-15 19:12
@bartosz-antosik This was actually https://github.com/Microsoft/vscode/issues/56317#issuecomment-413247158.

**Comment by bartosz-antosik** [comment] 2018-08-15 19:40
@nealot Many thanks. This may be actually an explanation to some other issue I had recently!

**Comment by bartosz-antosik** [comment] 2018-08-17 10:50
Hi again! It seems that the above mentioned issue [56317](https://github.com/Microsoft/vscode/issues/56317) has been addressed in version 1.26.1. Could you tell me if you see any change?

It was not happening in any of my versions so I cannot really tell...

**Comment by nealot** [comment] 2018-08-17 14:55
I don't see the problem anymore, seems like it was resolved.
