### ISSUE TITLE
Cannot select other language than English

### ISSUE THREAD

**Issue by kubics** [bartosz-antosik/vscode-spellright#106] opened 2018-01-04 12:05 UTC
I have installed SpellRight in latest VSCode 1.19.1 on Windows 10 Pro. 

I do have Slovak language installed in "Country and region", which is not selected as Windows display language. 
![image](https://user-images.githubusercontent.com/3758112/34562662-a80bf338-f14f-11e7-9c95-ffdfb203e4d0.png)

I do have also Slovak proofing tools (dictionary) installed in MS Office 2016 and I am using it for proofing.
![image](https://user-images.githubusercontent.com/3758112/34562681-baa1e62e-f14f-11e7-8bcb-8172d0be30dc.png)

However, SpellRight is still only offering English language. I have also tried "spellright.language": "sk-SK", user setting, but this did not help as well.
![image](https://user-images.githubusercontent.com/3758112/34562700-d1770910-f14f-11e7-9a31-dc1d8c98655b.png)

Thanks in advance for any advice.

**Comment by bartosz-antosik** [comment] 2018-01-04 12:39
Hmmmm, seems to workshere:

![image](https://user-images.githubusercontent.com/20492548/34563858-b62e4e98-f154-11e7-9e82-74304afb53f4.png)

You have restarted things of course?

**Comment by kubics** [comment] 2018-01-04 13:01
Yes, I restarted several times. I have also tried to completely change my system language to Slovak, but nothing helps. I am x64 system with x64 office and x64 VSCode.

**Comment by bartosz-antosik** [comment] 2018-01-04 13:08
Everything seems to be exactly as here (x64, English UI, etc., etc.). Let me meditate on this.

**Comment by bartosz-antosik** [comment] 2018-01-04 14:49
Could you please try to install some other language for a test? Any wester from among those listed on my picture?

**Comment by kubics** [comment] 2018-01-04 15:53
I have tried to install German as system language as well as proofing tools for office, but nothing changed. I have also found that French and Spanish proofing tools were also already preinstalled on my system, but I do not see them in VSCode.

**Comment by bartosz-antosik** [comment] 2018-01-04 17:01
Do I understand correctly that no matter what you have installed you can see only `English`?

Could you try to set `groupDictionaries` to false?

**Comment by kubics** [comment] 2018-01-05 07:46
Yes, you are right. I only can see English. After groupDictionaries set to false I see this:
![image](https://user-images.githubusercontent.com/3758112/34599869-e0de3388-f1f4-11e7-8ce5-1593f3305745.png)

**Comment by bartosz-antosik** [comment] 2018-01-05 09:54
Incredible! I will try to prepare for you a test version which will dump some more debug information and as you to install it & pass the input. I see no other way to deal with this.

**Comment by bartosz-antosik** [comment] 2018-01-05 12:32
I have installed Slovak on a second machine and it did not appear immediately in restarted VSCode. Had a hope to be able to debug the issue but after the reboot it has appeared. Tough case.

**Comment by bartosz-antosik** [comment] 2018-01-08 09:03
I still cannot see anything that could be wrong with on the Spell Right's part.

Could you please do a test for me?

I have prepared a version with some small additional debug information printed. Please download:

https://drive.google.com/file/d/1Z2narKQ1gW26JxpQ1K83B6lyIpMrTpFe/view?usp=sharing

Then install it manually from VSIX file.

Then once you start VSCode please show Console of Developer Tools (Help -> Toggle Developer Tools) and there should appear an information for the loaded dictionaries:

![image](https://user-images.githubusercontent.com/20492548/34664191-f6416656-f45a-11e7-817a-68b55cdd82ca.png)

Could you tell me what information is displayed there (all the lines that have form `[spellright] Adding dictionary [xxx]`)?

**Comment by kubics** [comment] 2018-01-08 09:23
Thanks for your effort. The console log contains exactly information corresponding to my options in listbox:
![image](https://user-images.githubusercontent.com/3758112/34664801-d8d542ce-f45d-11e7-8604-0f4777e6bfea.png)

These 4 lines appear in the log after every single character I write into any file.

**Comment by bartosz-antosik** [comment] 2018-01-08 09:34
It looks like the underlying layer, a library I am using from the very beginning of the time [node-spellchecker
](https://github.com/atom/node-spellchecker) has some problem in some unspecified conditions. Very bad that I cannot reproduce this.

**Comment by bartosz-antosik** [comment] 2018-01-08 09:38
You may please consider a workaround - there is a way to run the extension using hunspell spell checker instead of system spellchecker. Then you would have to download desired dictionaries like it is described in `Linux and Windows 7` section.

To do this set environment variable SPELLCHECKER_PREFER_HUNSPELL (Right Click on My Computer -> Properties -> Advanced system settings -> Environment Variables... -> System variables OR User variables for XXX -> New... -> Variable name = SPELLCHECKER_PREFER_HUNSPELL, Variable Value = 1) - of course if you can set these (user rights).

Restart VSCode & then the extension should use HUNSPELL spelling API, not Windows native one.

**Comment by bartosz-antosik** [comment] 2018-01-08 09:51
Just out of the blue: Do you have language switch in Taskbar ON?

![image](https://user-images.githubusercontent.com/20492548/34665775-d0874b68-f461-11e7-9fca-70ee495258c1.png)

**Comment by kubics** [comment] 2018-01-08 09:53
Yes, I do. Currently looking like this:
![image](https://user-images.githubusercontent.com/3758112/34665884-2d35c57e-f462-11e7-95ac-451c87514d8d.png)

**Comment by bartosz-antosik** [comment] 2018-01-08 10:21
Last attempt! I have compiled a sample from [here](https://github.com/Microsoft/Windows-classic-samples/tree/master/Samples/SpellCheckerClient) it dumps this on my machine:

![image](https://user-images.githubusercontent.com/20492548/34666668-c9664d12-f465-11e7-82de-a50e4b57c37e.png)

Could you please download it here:

https://drive.google.com/file/d/1wwMP2DYb0v0wsotXzi8EIp-p8exT4ljx/view?usp=sharing

And then show me what does it dump on your machine?

**Comment by kubics** [comment] 2018-01-08 13:15
Hmm, this is interesting. When I run it, I get this:
![image](https://user-images.githubusercontent.com/3758112/34672244-0847f2de-f47e-11e7-89bd-4e34158b7ef2.png)

Now the questions is, whether I only have problem, because it is looking for DEBUG version of the library, or the problem would be there also without "D".

I have already tried to repair my office installation and also reinstalled or repaired all these C++ redistributables, but nothing helped. Could you build it for me in release mode? Or do you have another idea of what could be the problem?
THX

**Comment by kubics** [comment] 2018-01-08 13:17
BTW, both vcruntime140.dll and vcruntime140d.dll are there in my c:\windows\system32

**Comment by bartosz-antosik** [comment] 2018-01-08 13:25
Sorry. Default build settings in VS2017. No idea it could result in something like this. Here is built with defaults of Release settings:

https://drive.google.com/file/d/1GPtE1nNAtOrS2S46lBq0kWTB5o9MqwZ-/view?usp=sharing

**Comment by kubics** [comment] 2018-01-08 13:36
Here is the result:
>Available languages:
>en-CA
>en-LR
>en-PH
>en-US

From this it seems that your extension is OK but there is something with my system / office installation.

**Comment by bartosz-antosik** [comment] 2018-01-08 13:39
By the looks of it. Gosh. For the moment I am officially out of ideas.

**Comment by bartosz-antosik** [comment] 2018-01-08 13:39
Many thanks for the tests anyway.

**Comment by kubics** [comment] 2018-01-09 08:27
Just to let you know... I have found out that languages offered to VS Code are absolutely independent on my office setup. I can even uninstall office completely and uninstall all language packs and proofing tools or I can make fresh install of the Office in SK language and it has no influence. Only languages that are offered are always the same languages that were preinstalled with windows and it doesn't matter whether there is proofing file for these languages or not.

Thanks for all your help. This seems to be some specific windows setup issue on my side.

**Comment by bartosz-antosik** [comment] 2018-01-09 09:48
Thanks for the update. I suppose, but have not been able to confirm this, that Office and Windows 8+ Spelling API are two independent things. Office works on other platforms (e.g. Windows 7) which do not have the Spelling API. Nevertheless I am disappointed about Windows. So far I had one unresolved issue #53 very similar to this. On the other hand there was the issue #23 which proofs that you can use multiple spelling languages on Single Language Windows edition...

I don't know how related this is but I have no Office installed. Just OneNote. Don't know whether this counts... ;-)

Looks like there is something possibly off course with spelling API.

I will close this thread. Shall you have any updates please post them here, maybe we will be able to reopen the issue with some solution.

**Closed by bartosz-antosik** 2018-01-09 09:48 UTC
Labels: invalid

**Comment by Magnati** [comment] 2019-09-05 15:43
Hello @bartosz-antosik and @kubics ,

I ran into the same issue but found a solution. 
The problem is that only admins can install certain parts of a language package under windows.
In our case it is the _"General Input"_ part of a language package which seems not to be installed when selected from a normal account.

So:
1. you have to Log-In via the admin-account
2. their you go as described to `settings->language&date->language`, and add your preferred language
    - in contrary to a normal account, in an admin account, all additional supported icons (like handwriting, text-to-speech etc.) are listed in the overview
    - although, once a language is selected, you have several more checkboxes to select certain parts of the package to be installed or not
    - **Note:** You need to wait until the whole package is installed, **the progress-bar is misleading** because it shows only the install finalization of the obligatory _"display language"_ part of the language package (because of course it does... :P ). 
You either wait until all supported icons  (like handwriting, text-to-speech etc.) appear or you check yourself by click on the language from the list and check in the options window the installation status. 
3. once installed you can go to any normal account and `spellright `will find the new installed languages
    - this works even if the particular language is not installed in the normal account!
The new installed Languages are not even shown in the language settings of the account  (because of course it does... :P )

On my system this behaviour was reproducible, and as a long time (annoyed) windows user this feels window-ish to me, which means it is probably intended behaviour.

**Comment by bartosz-antosik** [comment] 2019-09-05 16:06
@Magnati You are a genius! Yest all this seems annoying and total mystery to me!

**Comment by Magnati** [comment] 2019-09-05 16:12
Thanks! :)

It would be good to get at least one confirmation in one of the three issues, but than you could add this hint to Your README.md

By the way, apart from the windows-holes-of-unfortune, thank you for this great package!

**Comment by bartosz-antosik** [comment] 2019-09-05 16:14
Thank you! I will of course add this to README in next iteration!

**Comment by M-orpheus** [comment] 2019-12-14 00:32
I installed Chinese, but it didn't show up. 
By the way, in "Microsoft Word", the spell-check package works correctly。

**Comment by Magnati** [comment] 2020-01-07 10:30
@M-orpheus 
Just to clarify: You installed from an admin account AND the chinese language package supports the "General Input" part?

**Comment by Tututuu** [comment] 2021-04-25 16:16
@Magnati Hello, how can you check whether the language package support the "General Input" part?

**Comment by AndreasLuckert** [comment] 2021-06-11 20:49
How do you actually install a language/dictionary in this extension? In my case, not even English is offered. It's just empty when I run `Spellcheck: Select dictionary (language)`

**Comment by VipSaran** [comment] 2023-04-14 08:49
> Just to let you know... I have found out that languages offered to VS Code are absolutely independent on my office setup. I can even uninstall office completely and uninstall all language packs and proofing tools or I can make fresh install of the Office in SK language and it has no influence. Only languages that are offered are always the same languages that were preinstalled with windows and it doesn't matter whether there is proofing file for these languages or not.
> 
> Thanks for all your help. This seems to be some specific windows setup issue on my side.
> 
> I will rather try the hunspell now.

Not specific to you as I have exactly the same problem with all the same steps reproducible up to this comment.

Setting `SPELLCHECKER_PREFER_HUNSPELL` removed _all_ languages for me also.

Thanks to hints suggested [here](https://github.com/bartosz-antosik/vscode-spellright/issues/106#issuecomment-528431502), I already had the language pack installed, but what fixed it for me was installing "Basic typing" for the language:
![image](https://user-images.githubusercontent.com/995948/231993441-3053799d-a139-4de6-99b3-7cf193b1e964.png)

After that VSC/SpellRight finally picked up Croatian.

**Comment by ATilland** [comment] 2023-06-28 07:08
The solution of @Magnati solved my problem that was very similar. Thanks
