### ISSUE TITLE
Dictionary not available when launching VSC in Win10 using "Run As Administrator"

### ISSUE THREAD

**Issue by mscavuzz04** [bartosz-antosik/vscode-spellright#72] opened 2017-10-04 22:10 UTC
I log into my Windows machine with a non-admin account to perform general tasks.  I launch all of my tools using the "Run as administrator" option and use my Active Directory admin account.

When I launch VSC using the "Run as administrator" option and use my admin credentials, there are no dictionaries to select.
![screenshot](https://user-images.githubusercontent.com/32527892/31202107-8d2a801c-a91e-11e7-9a7e-13e707bf4b26.png)

**Comment by bartosz-antosik** [comment] 2017-10-04 23:10
I will probably have some more questions because when I "Run as administrator" it does show all dictionaries. But, my regular user is a domain user which is also in Administrators group.

Is your non-admin user a domain or local user?

**Comment by bartosz-antosik** [comment] 2017-10-04 23:23
I have switched regular user to User. Still when I run VSCode as administrator does show all dictionaries.

Have no idea how to reproduce this.

Isn't there anything related to it in the system logs?

**Comment by bartosz-antosik** [comment] 2017-10-06 11:57
I really cannot reproduce this issue. Without any help I will close this thread.

**Comment by mscavuzz04** [comment] 2017-10-06 13:58
Sorry for the delay in my response.

My configuration:

·         Operating System: Windows 10

·         “User Account A” is a member of the local “Users” group

·         “User Account B” is a member of the local “Administrators” group

Usage:
I log into my computer using “User Account A” to perform non-admin work.  I right click on VS Code and select “Run as administrator” and use “User Account B” to launch the application.  When launching VS Code this way, I do not get a dictionary to select within the Spell Right extension.

Thank you for looking into this issue.

**Comment by bartosz-antosik** [comment] 2017-10-06 17:00
Thank you for the update. It helped me re-create the problem.

Unfortunately this is a Windows problem. It manifests in Windows System log with the entry:

Error DistributedCOM 10016

with the following (or simillar) details:

```
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{D63B10C5-BB46-4990-A94F-E40B9D520160}
 and APPID 
{9CA88EE3-ACB7-47C8-AFC4-AB702511C276}
 to the user XXX\YYYY SID (S-1-5-21-3393638723-4152832952-1479321352-1001) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.
```

(XXXX\YYYY is masked machine & user name)

You may verify that you have this error popping out in Windows System Event Log.

Spell Right uses Windows Spelling API and this API uses COM subsystem to communicate with API. This error prevents communication with COM object for some specific user (listed in the log entry details).

Once you search Internet for any of the details of the error you will find some solutions on how to resolve this (e.g. [this](https://shauncassells.wordpress.com/2015/09/28/windows-10-event-10016-fix-the-application-specific-permission-settings-do-not-grant-local-activation-permission-for-the-com-server-application-with-clsid-d63b10c5-bb46-4990-a94f-e40b9d520160-and-a/)).

This alas DID NOT WORK FOR ME.

Maybe because I was using specific setup (Local user with Administrators rights). I cannot tell.

You may try these solutions but I really cannot advice on this. This is a much bigger issue with windows. An old one as well.

There is however another way: As the bindings realize that the COM object cannot be established they switch to using HUNSPELL built in spell checker. HUNSPELL however requires some dictionaries. This is why there is empty list because you have no HUNSPELL dictionaries installed. Where to get them and how to install them is described in README.md section **Dictionaries**/**Linux and Windows 7**.

So you may still try to use Spell Right it will however be using different back-end.

**Closed by bartosz-antosik** 2017-10-06 17:00 UTC
Labels: help wanted

**Comment by mscavuzz04** [comment] 2017-10-06 19:40
No problem.  Thank you for the quick response.  Much appreciated.
