### ISSUE TITLE
"Cannot read properties of null" error in VS Code v1.78

### ISSUE THREAD

**Issue by craigtp** [bartosz-antosik/vscode-spellright#549] opened 2023-05-04 09:01 UTC
VS Code updated to Electron 22 and [this bug](https://github.com/bartosz-antosik/vscode-spellright/issues/513) is now happening again.
https://code.visualstudio.com/updates/v1_78#_electron-22-update

Version: 1.78.0 (user setup)
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:09:00.748Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

```
[error] TypeError: Cannot read properties of null (reading 'Spellchecker')
	at Object.<anonymous> (c:\Users\username\.vscode\extensions\ban.spellright-3.0.112\lib\bindings.js:46:25)
```

_Originally posted by @reduckted in https://github.com/bartosz-antosik/vscode-spellright/issues/513#issuecomment-1533914159_

**Comment by reduckted** [comment] 2023-05-11 11:50
I believe this had been fixed in the latest version.

**Comment by powerunlimited** [comment] 2023-09-08 05:34
Seems like it is happening again with v1.82.0

**Comment by Nummer42O** [comment] 2024-04-06 12:57
Happening too for me. Version info:

Version: 1.88.0
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:25:57.039Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 5.15.0-101-generic

**Comment by bartosz-antosik** [comment] 2024-04-10 09:31
Hi! The extension binary dependencies, root cause of the above, has been updated. It took far more than usually/expected mainly because of some nasty bug in `nan` (https://github.com/nodejs/nan/issues/936#issuecomment-1961938183). Never mind, should work for now.

**Closed by bartosz-antosik** 2024-04-10 09:31 UTC
