### ISSUE TITLE
Spell Check not running until I make changes to the file

### ISSUE THREAD

**Issue by george8008** [bartosz-antosik/vscode-spellright#174] opened 2018-07-01 21:49 UTC
The issue I'm having is that the spell checker doesn't run when opening a file selected from the explorer. whether I single click or double click the file. The spell checker only runs once I make a change to the file. I don't have to save the file first but I do have to make a change. 

I can clearly see the spell checking is ON (English - Australia) for the file but the spell check does not run until i make a change.

![image](https://user-images.githubusercontent.com/25045317/42139129-51c6088e-7dcb-11e8-891e-df4ed91ee5c3.png)

Attached VSCode "about" info. I am running VSCode on windows 10 Pro.

**Comment by bartosz-antosik** [comment] 2018-07-01 22:17
Thanks for reporting! I will have a look into this and may have further questions.

**Comment by bartosz-antosik** [comment] 2018-07-04 18:15
It is not clear to me whether I can reproduce the problem. I have tried many ways of opening the file and it seemed to me that it always get checked properly on start. I have however noticed that there is a problem when there are two panes aside with files to be spelled, then one file is checked the other is not. In a quest to repair this I have changed the way Spell Right refreshes a bit (quite a bit actually) and I would like you to try whether it changes anything in the problem you describe. Here you can download version 2.5.8:

https://drive.google.com/open?id=14xQYQqSuQ20GzxGZYWSiDxKiD7Tg12Nc

If you could install it from VSIX archive and give it a try & please report whether you observe a change in it's behavior would be very helpful.

**Comment by bartosz-antosik** [comment] 2018-07-10 12:57
I could not reproduce the behavior described above. Version 2.5.16 has changed the way it spells newly opened documents and I suppose it may affect this issue. I will close this issue for now and revive it once it returns in any form.

**Closed by bartosz-antosik** 2018-07-10 12:57 UTC
Labels: help wanted

**Comment by george8008** [comment] 2018-07-10 21:14
Sorry for the late reply. I just tried our Version 2.5.16 and it has fixed the problem. files are now spell checked as soon as i open them. Thanks for looking into this.

**Comment by bartosz-antosik** [comment] 2018-07-10 22:16
You are welcome! Thank you for updating review rank.

**Comment by bartosz-antosik** [comment] 2018-07-11 08:45
Yes it does. Happy to help.
