### ISSUE TITLE
Add "Turn OFF for current file"

### ISSUE THREAD

**Issue by swarnendubiswas** [bartosz-antosik/vscode-spellright#172] opened 2018-06-20 22:55 UTC
I want to selectively turn off spell checking for certain files with absolute paths. There are two observations I would like to make. 

1. I have updated `spellright.ignoreFiles` with the absolute path as follows. 
```
    "spellright.ignoreFiles": [
        "**/.gitignore",
        "/h2/sbiswas/Desktop/commands.md",
        "/h2/sbiswas/Desktop/arc-experiments.md"
    ],
```
Spell check is turned off for the first path but is on for the second as show below. So I am confused, does `spellright.ignoreFiles` accept absolute paths?

![screenshot from 2018-06-20 17-52-36](https://user-images.githubusercontent.com/7343807/41688759-fb52c3c8-74b2-11e8-829d-cf5a17497e05.png)

![screenshot from 2018-06-20 17-52-52](https://user-images.githubusercontent.com/7343807/41688767-001b512c-74b3-11e8-8d80-6dca61143927.png)

`.spellignore` is an option, but some of my files are not in any projects. 

2) It would be good to add a command to turn off spell checking for the given file (not by file type) instead of having to manually edit `settings.json`.

**Comment by bartosz-antosik** [comment] 2018-06-21 17:39
Hi! GitIgnore patterns which work for both `spellright.ignoreFiles` and `.spellignore` file are by they nature relative to some root. That is workspace root in case of VSCode. I have added absolute path for both `ignore` methods (it is not published yet however) but I am still unsure whether the whole idea is good.

Could you please tell me why do you need absolute path?

Wouldn't it be enough to eliminate for example `commands.md`?

**Comment by swarnendubiswas** [comment] 2018-06-21 19:06
I have many files littered around which are not part of any projects. I use these files to store notes about many things. For example, my `commands.md` contain often-used and difficult-to-remember shell commands for future reference. SpellRight would report several spelling errors for these files unless I turn off spell checking. 

What I am getting at is a requirement where I turn off spell checking for specific files. Just eliminating `commands.md` as a pattern would mean that spell checking could be turned off for an important project where I have a file with the same file name. A tedious option would be to have a project `settings.json` override the global `spellright.ignoreFiles` but then I need to remember to do it for every project that might have a file named `commands.md`.

**Comment by bartosz-antosik** [comment] 2018-06-28 09:55
Absolute location should be implemented in version 2.5.4.

Please give it a try and let me know if it works for you.

**Comment by swarnendubiswas** [comment] 2018-06-29 20:54
Unfortunately, no. I continue to get the spelling notifications.

**Comment by bartosz-antosik** [comment] 2018-07-04 18:17
It is not clear to me whether I can reproduce the problem. Absolute path seemed to be working fine for me on Linux (a Kubuntu actually). I have changed the way settings are refreshed and I would like you to try whether it changes anything in the situation you describe. Here you can download version 2.5.8:

https://drive.google.com/open?id=14xQYQqSuQ20GzxGZYWSiDxKiD7Tg12Nc

If you could install it from VSIX archive and give it a try & please report whether you observe a change in it's behavior would be very helpful.

**Comment by swarnendubiswas** [comment] 2018-07-04 18:35
Sure, I will give it a try.

**Comment by bartosz-antosik** [comment] 2018-07-05 16:54
Hello, thank you for giving it a go! Is it enabled for `/h2/sbiswas/Desktop/vscode-linux-shortcuts.md`?

**Comment by swarnendubiswas** [comment] 2018-07-05 16:55
Yes, that is the screenshot I had attached.

**Comment by bartosz-antosik** [comment] 2018-07-05 17:03
Oh, sorry, haven't realized that it is the same file provided in absolute and user root related manner.

**Comment by bartosz-antosik** [comment] 2018-07-05 17:32
I really have problem catching the problem. It seems to be quite ok here.

Could you please do in console:

`readlink -f vscode-linux-shortcuts.md`

In the directory where the file exists?

**Comment by swarnendubiswas** [comment] 2018-07-05 18:18
```
[sbiswas@consensus Desktop]$ readlink -f vscode-linux-shortcuts.md 
/h2/sbiswas/Desktop/vscode-linux-shortcuts.md
```

Hmm, I am also having trouble to think what else could be the issue.

**Comment by bartosz-antosik** [comment] 2018-07-05 18:53
This is how it looks here, tested on Kubuntu, 18.04:

![screenshot_20180705_203325](https://user-images.githubusercontent.com/20492548/42341358-19d2a520-8093-11e8-9045-53b63cf999ec.png)

I will think of another idea and maybe have same kind request for you to test the thing.

**Comment by bartosz-antosik** [comment] 2018-07-05 19:45
I have changed the method of comparing file paths. If you could maybe try:

https://drive.google.com/open?id=1XlJZWaoaQeHD-x-DKxxbKZzeNnmua69t

**Comment by swarnendubiswas** [comment] 2018-07-13 23:00
Sorry this does not work.

**Comment by bartosz-antosik** [comment] 2018-07-19 11:31
I am sorry for getting back with this after few days, but I have done some tests and is teems to be working for me and I really have no clue why this does not work for you. Is there a chance you could debug this?

It happens in `spellright.js` from line 643 on.

**Comment by bartosz-antosik** [comment] 2018-07-31 10:00
I am relay sorry but I cannot do anything more without some help. I will close it now if you find more findings please report here I will reopen the thread then.

**Closed by bartosz-antosik** 2018-07-31 10:00 UTC
Labels: enhancement
