### ISSUE TITLE
No squiggles with VS Code 1.17.1 x64 on Win7

### ISSUE THREAD

**Issue by Molinarius** [bartosz-antosik/vscode-spellright#79] opened 2017-10-17 12:00 UTC
I can’t get Spell Right to display squiggles (the red underlining) for wrong spelled words in VS Code 1.17.1 x64 on Windows 7.  (To be honest, it stopped working some time ago, but I only started to investigate today.) On another Win 7 machine, it worked fine with VS Code 1.14.2 x86, but after updating to 1.17.1 x64, again no squiggles.

Selecting language works. Tried different dictionaries. Uninstalled and reinstalled. Nothing in Output, Debug Console or Problems, even after setting global.SPELLRIGHT_DEBUG_OUTPUT to true. Not using custom Spell Right settings, all other extensions disabled.

**Comment by bartosz-antosik** [comment] 2017-10-17 12:05
Could you show me the configuration settings you use (User/Workspace)?

**Comment by Molinarius** [comment] 2017-10-17 12:07
Don’t have workspace settings. User:

// Place your settings in this file to overwrite the default settings
{
    "editor.tabSize": 4,
    "editor.renderWhitespace": "boundary",
    "editor.fontSize": 13,
    "editor.wordWrap": "on",
    "editor.wrappingIndent": "indent",
    "editor.rulers": [100, 150],
    "extensions.autoUpdate": false,
    "telemetry.enableTelemetry": false,
    "http.proxy": "https://xxxx:8080",
    "files.encoding": "utf8bom",
    "editor.mouseWheelZoom": true,
    "markdown-pdf.type": "html",
    "markdown-pdf.styles": ["xxxx\\Martins_Markdown_PDF_Style.css"],
    "window.zoomLevel": 0,
    "workbench.colorTheme": "Default Light+",
    "files.autoGuessEncoding": true,
    "csharp.suppressDotnetInstallWarning": true,
    "editor.smoothScrolling": true,
    "C_Cpp.intelliSenseEngine": "Default"
}

**Comment by Molinarius** [comment] 2017-10-17 12:09
I just removed all of the settings. Same behaviour.

**Comment by bartosz-antosik** [comment] 2017-10-17 12:10
Thank you. Do not see anything that would influence the settings (I was thinking there is recently added setting `spellright.notificationClass` thought maybe accidentally it was set to something which would draw 'invisible' squiggles). Let me try to investigate.

**Comment by bartosz-antosik** [comment] 2017-10-17 13:06
Do you use it in a workspace or not? If NOT - could you try with workspace?

**Comment by bartosz-antosik** [comment] 2017-10-17 13:27
Before writing the comment above I did some test on Windows 7. I had a similar situation: VSCode 1.14.x on which it did not work, then I have upgraded to 1.17.2 it did not work either. Then I have realized that the problem is when using it without the Workspace (A Folder open). When used with workspace it seems to work fine. 

![image](https://user-images.githubusercontent.com/20492548/31667416-af31c1b2-b34f-11e7-9b46-d4ba04fd6322.png)

There is a patch prepared I just would like to have a confirmation that this is the problem.

**Comment by Molinarius** [comment] 2017-10-17 21:31
You are right, with 1.17.2 (didn't try it with an older version), it is working with a workspace and not working without a workspace. Please let me know if I can help you with the patch.

**Comment by bartosz-antosik** [comment] 2017-10-18 07:29
The fix was already prepared. I just needed confirmation that I am after the same thing. 

Should be fixed in version 1.2.22.

**Comment by bartosz-antosik** [comment] 2017-10-18 07:33
Oh, please let me know in this thread that it is fixed for you.

**Closed** 2017-10-18 07:33 UTC
Labels: help wanted

**Comment by Molinarius** [comment] 2017-10-18 07:57
Yes, it’s working with 1.2.22, with and without a workspace. Thank you very much!

**Comment by bartosz-antosik** [comment] 2017-10-18 08:41
Thank you for the update on this!
