### ISSUE TITLE
How to ignore `code` in Markdown using spellright.ignoreRegExps?

### ISSUE THREAD

**Issue by borekb** [bartosz-antosik/vscode-spellright#24] opened 2017-07-04 11:25 UTC
I want to suppress spell checking inside Markdown `code` words and I've got a feeling that `spellright.ignoreRegExps` will be the way to go, however, I can't figure out how to write that regexp. Could you provide an example please? Is it possible at all? I've tried:

```
    "spellright.ignoreRegExps": [
        "/`.*`/g"
    ]
```

which doesn't seem to work.

Thanks for an awesome extension BTW.

**Comment by bartosz-antosik** [comment] 2017-07-04 21:49
Sadly these regular expressions cannot do the work. They are matched after separation of the lexemes (words) at exactly the same place as `ignoreWords`.

I have added this to Markdown parser and it should now ignore inline code parts in version 1.0.24.

**Comment by bartosz-antosik** [comment] 2017-07-05 21:22
Please let me know if code ignoring in version 10.24 works for you.

**Comment by borekb** [comment] 2017-07-06 09:38
Yes it's working great! On a similar front, I think the links in MD link syntax should also be skipped:

```
[test](http://example.com)
       ^^^^^^^^^^^^^^^^^^ don't spell check this
```

To overload this comment even more, is there an easy way to add some words to `ignoreWords` or do I need to do that manually?

**Comment by bartosz-antosik** [comment] 2017-07-06 20:34
This is strange - e-mails & URL should be excluded from spelling (globally) from version 1.0.10. Could you please provide an example URL that is spelled?

No, there is no menu for adding this. This has to be done manually. This is a bit "by design" as I was aiming in as low-profile GUI as possible. Also I am not sure if it is possible to have information about word under cursor when providing context menu actions - if it would all spellcheckers would use this instead of adding diagnostics to the list. This would allow to scan for proper forms of words while popping the menu, which would speed spelling a lot - currently it takes a lot of time to provide correctly spelled words than to check if the word is spelled correctly or not.

**Comment by bartosz-antosik** [comment] 2017-07-06 20:46
But maybe you are right - there could be an action, probably with unassigned key to add word to ignored word list. Let me think this through.

**Comment by borekb** [comment] 2017-07-06 21:23
You're right, URLs are not spell checked, my actual examples are relative links like this:

![image](https://user-images.githubusercontent.com/101152/27933534-2c3270ac-62a2-11e7-8f85-18b6b7083db7.png)

**Comment by bartosz-antosik** [comment] 2017-07-06 21:25
If I could please get this in text! ;-)

**Comment by borekb** [comment] 2017-07-06 21:25
```md
- [PhpStorm setup](#phpstorm)
- [Writing code](#writing-code)
- [Debugging](#debugging)
- [Testing](#testing)
- [Frontend development](#frontend-development)
- [Production build](#production-build)
- [Docker tips](#docker-tips)
```

**Comment by bartosz-antosik** [comment] 2017-07-06 22:29
Wait! I have missed one important thing - when you have a word underlined as misspelled then once you press correct button (`Ctrl+.`) you get a menu with suggestions which has two last items "Add "misspelled" to Workspace ignore list" and "Add "misspelled" to global ignore list" - have you considered these?

![add-to-ignore](https://user-images.githubusercontent.com/20492548/27935394-2da2a1d8-62ab-11e7-88ee-a35cd8fe03e4.png)

I tend not to use custom dictionaries (a.k.a. Ignore Lists). That's maybe why I have forgot them.

**Comment by borekb** [comment] 2017-07-06 22:32
OMG how could I have missed this? :) Exactly what I'm looking for.

**Comment by bartosz-antosik** [comment] 2017-07-06 22:33
Seems close. I will close this thread, please examine these and report if that's very off what you need. ;-)

**Closed by bartosz-antosik** 2017-07-06 22:33 UTC
